### ISSUE TITLE
compile error v1.0.0 on Linux : solved

### ISSUE THREAD

**Issue by tissatussa** [Mergener/lunachess#8]
hi,

at first i was not able to compile your source; both `git clone` and asset ZIP have same error .. i followed the instructions :

cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

```
[....]
[ 93%] Linking CXX executable lunatest
[ 93%] Built target lunatest
[ 96%] Building CXX object CMakeFiles/lunatuner.dir/src/lunatuner/main.cpp.o
/tmp/ccGOURut.s: Assembler messages:
/tmp/ccGOURut.s:9: Error: file not found: /home/roelof/Compiled/lunachess/src/lunatuner/priorities.json
make[2]: *** [CMakeFiles/lunatuner.dir/build.make:76: CMakeFiles/lunatuner.dir/src/lunatuner/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:239: CMakeFiles/lunatuner.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

indeed the file `src/lunatuner/priorities.json` is missing .. so i just added a file called `priorities.json` in that folder - it's an empty json, just { }

then compiling went well !
maybe it's a Windows issue ? something giving troubles on Linux ? i have cmake version 3.26.3

**Comment by Mergener** [comment]
This was actually an oversight by me! I didn't push the file. However, this should only prevent you from compiling the evaluation tuner, not the engine itself. Anyway, it's an important oversight. Thank you for reporting it!

**Comment by Mergener** [comment]
Your issue was fixed in the main branch and I've added a note in the 1.0 release mentioning the problem (also a sample `priorities.json` was attached).

I'm now closing this issue as it is solved.
Once again, thank you for your contribution! :)

**Comment by tissatussa** [comment]
[ sorry to comment on this closed Issue ]

Indeed your newest v1.1 source code compiles without any error or warning. However, it still shows "v1.0.0", and no version number is displayed after the `uci` command.
